sudo: false
dist: trusty
lang: bash

addons:
  apt:
    update: false
    packages:
    - shellcheck

env:
  # Whilst this directory is already on PATH, it's after /usr/bin/local.
  # This prevents the older shellcheck in /usr/bin/local being used instead.
  - PATH="$HOME/bin:$PATH"
install:
  - curl -sSfL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
  - unzip /tmp/terraform.zip -d "$HOME/bin"
  - terraform --version
  - shellcheck --version
script:
  - ./runtests.sh
